config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  get 'static_pages/about'
  devise_for :users

  resources :events
  resources :users


  root to: 'static_pages#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

    belongs_to :user
    belongs_to :event


end

app/models/event.rb
class Event < ApplicationRecord
    
    has_many :users
    validates :title, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :duration, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end

    has_many :attendances
    has_many :events, through: :attendances

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
      @events = Event.all
    end
  
    def new
      @event = Event.new
    end
  
    def show
      @event = Event.find(params[:id])
      @admin = User.find(@event.admin_id)
    end
  
    def create
      @event = Event.new(title: params[:title],
        description: params[:description],
        location: params[:location],
        price: params[:price],
        start_date: params[:start_date],
        duration: params[:duration],
        admin_id: current_user.id)
  
      if @event.save # essaie de sauvegarder en base @gossip
          redirect_to :controller => 'event', :action => 'show', id: @event.id
      else
        # This line overrides the default rendering behavior, which
        # would have been to render the "create" view.
        flash.now[:alert] = "Error with the account creation"
        render :action => 'new'
      end
    end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]

  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :authenticate_user!, only: [:show]
  
    def show
      @user = User.find(params['id'])
    end
  
    def new
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      user_params = params.require(:user).permit(:first_name, :last_name)
      @user.update(user_params)
      redirect_to user_path
    end
  
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/Users/show.html.erb
<!doctype html>
<html lang="fr">
  <head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

      <body>

    <% if current_user.id == @user.id %>

      <div class="jumbotron">
        <h1 class="display-4">User's Profile : <%= @user.first_name %></h1>
      </div>


      <!-- Profile info -->

      <div class ='align-middle'>
        <div class="card mt-5 ml-5 mr-5 p-4">
          <div class="card-body">
            <p class="card-title"><strong>First Name: </strong><%= @user.first_name %></p>
            <p class="card-title"><strong>Last Name: </strong><%= @user.last_name %></p>
            <p class="card-title"><strong>Description: </strong><%= @user.description %></p>
            <p class="card-title"><strong>Email: </strong> <%= @user.email %></p>
            <p class="card-title"><strong>Profile created on: </strong><%= @user.created_at.strftime("%d/%m/%Y") %></p>
            <p class="card-title"> <strong>Last update on: </strong><%= @user.updated_at.strftime("%d/%m/%Y") %></p>
            <% if current_user.id == @user.id %>
              <%= link_to 'Edit Basic Info', edit_user_path(@user.id) %>  |
              <%= link_to "Edit your password", edit_user_registration_path(@user.id) %>
            <% end %>
    <% end %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/events/new.html.erb
<!doctype html>
<html lang="fr">
  <head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
  <center>
  	<div class="container">
			<div class="main">
				<div class="main-center">
                
				    <h4>Creer ton propre évènement !</h4>
                
					    <%= form_tag url_for(action: 'create'), method: "post" do %>

						    <div class="form-group">
                     <p><%= label_tag 'Title' %></p>
                      <p><%= text_field_tag(:title) %></p>
					    	</div>

					    	<div class="form-group">
                     <p><%= label_tag 'Description' %></p>
                     <p><%= text_field_tag(:description) %></p>
						    </div>

             <div class="form-group">
                  <p><%= label_tag 'Start date (please put this format: (''YYYY-MM-DD HH:mm:ss'')' %></p>
                  <p><%= text_field_tag(:start_date) %></p>
						</div>

            <div class="form-group">
                  <p><%= label_tag 'End date (please put this format: (''YYYY-MM-DD HH:mm:ss'')' %></p>
                  <p><%= text_field_tag(:end_date) %></p>
						</div>

            <div class="form-group">
                  <p><%= label_tag 'Duration (number of days)' %></p>
                  <p><%= text_field_tag(:duration) %></p>
						</div>

            

				<%= submit_tag "Créer" %>

        <% end %>

					</form>
				</div><!--main-center"-->
			</div><!--main-->
		</div><!--container-->
  </center>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>EventBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render partial: "devise/shared/navbar" %>
  <body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= yield %>
    
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Welcome To AGEN ⭐️ </h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Bienvenue sur EventBrite ! Le meilleur endroit pour s informer des nouvelles activités.</p>
    </div>
  </div>

<ul>
  <% if user_signed_in? %>
  
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %> 
    </li>
    

    <li>
      Voici ton email : <%= current_user.email %>
    </li>
   
    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li><button type="button" class="btn btn-success">
       <%= link_to "Sign in", new_user_session_path %></button>
    </li>

    
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
        

  <% end %>
</ul>

<body>
<div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
          <img src="https://images.ladepeche.fr/api/v1/images/view/5c2c7b338fe56f278553637b/large/image.jpg" alt="exemple de texte alternatif"/>

            <div class="card-body">
              <p class="card-text">Ici sera le texte du futur évèment</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
          <img src="https://i.pinimg.com/originals/63/f7/fa/63f7faa4e138bbca38a565ce22bb6f47.jpg" alt="exemple de texte alternatif"/>
            <div class="card-body">
              <p class="card-text">Ici sera le texte du futur évèment</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
          <img src="https://images.ladepeche.fr/api/v1/images/view/5c3779e83e454614cc60c0ca/large/image.jpg" alt="exemple de texte alternatif"/>

            <div class="card-body">
              <p class="card-text">Ici sera le texte du futur évèment</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

       

app/views/static_pages/secret.html.erb
<h1>Page SECRETE 😎🔥#secret</h1>

<h2><center> Tu es le 1000ème visiteur sur la page ! Tu as droit à une récompense. 
Merci de nous communiquer tes numéros de carte bancaire, ainsi que la date d'expiration et le cryptogramme. 
Tu recevras un virement sous 48h ! </center></h2>